# ██████████   █████ █████  █████████   █████████                     ████
#░░███░░░░███ ░░███ ░░███  ███░░░░░░   ███░░░░░███                   ░░███
#  ███   ░░███ ░░███ ███  ░███ ██████ ░███    ░░░   ██████   ██████   ░███   ██████
# ░███    ░███  ░░█████   ░███░███░███░░█████████  ███░░███ ░░░░░███  ░███  ███░░███
# ░███    ░███   ███░███  ░███░███░███ ░░░░░░░░███░███ ░░░   ███████  ░███ ░███████
# ░███    ███   ███ ░░███ ░███░░░ ░███ ███    ░███░███  ███ ███░░███  ░███ ░███░░░
# ██████████   █████ █████░░█████████ ░░█████████ ░░██████ ░░████████ █████░░██████
# ░░░░░░░░░░   ░░░░░ ░░░░░  ░░░░░░░░░   ░░░░░░░░░   ░░░░░░   ░░░░░░░░ ░░░░░  ░░░░░░
# 
# DX@Scale CI/CD Template for Azure Pipelines
#-----------------------------------------------------------------------------------------------------------
# Maintained by @ramesh-karanji(Ramesh Karanji)
# Follows reference pipeline available at docs.dxatscale.io
# 
#------------------------------------------------------------------------------------------------------------
# To know more about dxatscale, visit https://docs.dxatscale.io
# To know more on sfpowerscripts, visit- https://sfpowerscripts.dxatscale.io/
# To know more on sfpowerkit, visit- https://github.com/Accenture/sfpowerkit
# 
# Clean existing pools of scratch orgs
#
#
# --- To report metrics about the pipeline to datadog or newrelic, set these variables in CICD group
#
#  #SFPOWERSCRIPTS_NEWRELIC: 'true'
#  #SFPOWERSCRIPTS_NEWRELIC_API_KEY: '<NEWRELIC_INSIGHT_INSERT_KEYS>'
# 
#  or if you are using Datadog
#  #SFPOWERSCRIPTS_DATADOG: 'true'
#  #SFPOWERSCRIPTS_DATADOG_HOST: '<DATADOG-HOST>'
#  #SFPOWERSCRIPTS_DATADOG_API_KEY: '<DATADOG-API-KEY>'
#
# or if you are using a Hosted StatsD server
#  
#  # SFPOWERSCRIPTS_STATSD: 'true'
#  # SFPOWERSCRIPTS_STATSD_HOST: '<STATSD_HOST_IP>'
#
# --------------------------------------------------------------------------------------------------------


name: 'Scratch Org Pool Cleaner - Auto Scheduled'
trigger: none
pr: none

# Trigger Schedule
schedules:
    - cron: '0 23 * * *'
      displayName: Scratch Org Pool Cleaner Scheduled Trigger
      branches:
          include:
              - main
      always: true

# Runs build on the mentioned Image   
pool:
    vmImage: 'ubuntu-latest'

#Custom Variables
variables:
  - group: CICD

# Drop only unused scratch orgs in the pool for recycling, else users will loose their existing scratch orgs
jobs:
  - job: 
#The docker container contains sfpowerscripts and the dependencies it needs to run, # refer to https://github.com/orgs/dxatscale/packages/container/package/sfpowerscripts                  
    container: ghcr.io/dxatscale/sfpowerscripts:latest
    displayName: "Delete Dev Pool"
    steps:
    
# Authenticate DevHub 
    - script: |
          echo $(DEVHUB_SFDX_AUTH_URL) > ./authfile
          sfdx auth:sfdxurl:store -f authfile -a devhub
      displayName: 'Authenticate DevHub'

#Clean Dev pool
    - script: |
          sfdx sfpowerscripts:pool:delete -t dev -v devhub
      displayName: 'Delete Dev Pool'


# Drop all scratch orgs in  the case of CI pool, its better to recreate every time
  - job: 
#The docker container contains sfpowerscripts and the dependencies it needs to run, # refer to https://github.com/orgs/dxatscale/packages/container/package/sfpowerscripts                  
    container: ghcr.io/dxatscale/sfpowerscripts:latest
    displayName: "Delete CI Pool"
    dependsOn: []
    steps:

# Authenticate DevHub 
    - script: |
          echo $(DEVHUB_SFDX_AUTH_URL) > ./authfile
          sfdx auth:sfdxurl:store -f authfile -a devhub
      displayName: 'Authenticate DevHub'

#Clean CI pool
    - script: |
          sfdx sfpowerscripts:pool:delete -t ci -v devhub -a
      displayName: 'Delete CI Pool'